apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels: { owner: apps, team: web, cost-center: dev }
spec:
  replicas: 1
  selector: { matchLabels: { app: web } }
  template:
    metadata:
      labels: { app: web }
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports: [ { containerPort: 80 } ]
---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels: { owner: apps, team: web, cost-center: dev }
spec:
  selector: { app: web }
  ports: [ { port: 80, targetPort: 80 } ]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels: { owner: apps, team: web, cost-center: dev }
spec:
  replicas: 1
  selector: { matchLabels: { app: api} }
  template:
    metadata:
      labels: { app: api }
    spec:
      containers:
      - name: api
        image: ghcr.io/waltberry/demo-api:latest
        imagePullPolicy: IfNotPresent
        args: ["uvicorn","app.main:app","--host","0.0.0.0","--port","8080"]
        ports: [ { containerPort: 8080 } ]
---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels: { owner: apps, team: web, cost-center: dev }
spec:
  selector: { app: api }
  ports: [ { port: 8080, targetPort: 8080 } ]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels: { owner: apps, team: web, cost-center: dev }
spec:
  replicas: 1
  selector: { matchLabels: { app: worker } }
  template:
    metadata:
      labels: { app: worker }
    spec:
      containers:
      - name: worker
        image: python:3.11-slim
        command: ["bash","-lc","while true; do echo tick; sleep 30; done"]